lunch/urls.py
from django.conf.urls import url

from . import views

app_name = 'lunch'
urlpatterns = [
	# index /
    url(r'^$', views.index, name='index'),
    # /restaurant/add
    url(r'^restaurant/add$', views.add_restaurant, name='add_restaurant'),
    # /restaurant/<id>
    url(r'^restaurant/(?P<restaurant_id>[0-9]+)$', views.restaurant_detail, name='restaurant_detail')
]

lunchy/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	# 
	url(r'^', include('lunch.urls')),
    url(r'^admin/', admin.site.urls),
]

lunch/models.py
from __future__ import unicode_literals

from django.db import models

class Restaurant(models.Model):
	facebook_id = models.BigIntegerField(unique=True, null=True)
	name = models.CharField(max_length=100)
	
	def __unicode__(self):
		return self.name

class MealOption(models.Model):
	restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
	name = models.CharField(max_length=45)
	created_at = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.name

	@staticmethod
	def get_random():
		return MealOption.objects.order_by('?').first()

lunch/views.py
from django.shortcuts import render, get_object_or_404
from .models import MealOption, Restaurant
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import translation


def index(request):
    # temp: set locale to de_CH as this is our target at the moment
    user_language = 'de_CH'
    translation.activate(user_language)
    request.session[translation.LANGUAGE_SESSION_KEY] = user_language

    place = None
    if 'place' in request.session:
        place = request.session['place']

    # get a random restaurant
    restaurant = Restaurant.objects.order_by('?').first()
    # try to get a random meal, otherwise we'll just say "something" from <restaurant>
    if restaurant:
        meal = restaurant.mealoption_set.order_by('?').first()
    else:
        meal = None

    return render(request, 'lunch/index.html', {
        'meal_option': meal,
        'restaurant': restaurant,
        'place': place
        })


def restaurant_detail(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)

    # save meal option
    if 'meal_option' in request.POST:
        restaurant.mealoption_set.create(name=request.POST['meal_option'])
        return HttpResponseRedirect(reverse('lunch:restaurant_detail', args=(restaurant_id,)))

    return render(request, 'lunch/restaurant.html', {
        'restaurant': restaurant,
        'suggestion': MealOption.get_random()
        })


# todo: check for facebook_id or set to null
def add_restaurant(request):
    # save restaurant and redirect to index
    if 'restaurant' in request.POST and 'facebook_id' in request.POST:
        # use submitted facebook_id or default to null
        facebook_id = request.POST['facebook_id'] if request.POST['facebook_id'] else None
        restaurant = Restaurant(name=request.POST['restaurant'], facebook_id=facebook_id)
        restaurant.save()
        return HttpResponseRedirect(reverse('lunch:index'))
    else:
        return render(request, 'lunch/add_restaurant.html')

lunch/templates/lunch/add.html
{% extends 'lunch/base.html' %}

{% block content %}
<div class="card-block">
	<h4 class="card-title">Add a meal for {{ restaurant }}</h4>	

	<form action="{% url 'lunch:add' restaurant.id %}" method="post">
		{% csrf_token %}

		<fieldset class="form-group">
		  <input type="text" id="mealOption" class="form-control" placeholder="e.g. {{suggestion}}">
		</fieldset>
		
	</form>

	<div class="card-block">
		<a href="#" class="card-link">add</a>
		<a class="card-link" href="{% url 'lunch:restaurant' restaurant.id %}">back</a>
	</div>
</div>


{% endblock %}

lunch/templates/lunch/add_restaurant.html
{% extends 'lunch/base.html' %}
{% load staticfiles %}

{% block content %}
<form name="add_restaurant" action="{% url 'lunch:add_restaurant' %}" method="post">
	{% csrf_token %}
	<div id="search-form"></div>
</form>
{% endblock %}

{% block javascript %}
    {% include 'lunch/snippets/facebook_js_sdk.html' %}
{% endblock %}

lunch/templates/lunch/base.html
{% load staticfiles %}

<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title>Lunchy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'lunch/style.css' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
</head>
<body data-route="{{ request.resolver_match.url_name }}">
  
  <div class="container">
  	<div id="app-container" class="card">
  		{% block content %}{% endblock content %}
  	</div>
  </div>

    <footer class="footer">
        <div class="container">
            {% block footer %}
            {% endblock footer %}
        </div>
    </footer>

    <script src="{% static "lunch/app.js" %}"></script>
    {% block javascript %}
    {% endblock javascript %}
</body>
</html>

lunch/templates/lunch/index.html
{% extends 'lunch/base.html' %}
{% load i18n %}

{% block content %}

    {% if place %}
        {% include "lunch/meal_suggestion.html" %}
    {% else %}
        {% include "lunch/location_prompt.html" %}
    {% endif %}

{% endblock %}

{% block footer %}
	{% url 'lunch:add_restaurant' as add_link %}
	{% blocktrans %}<a href="{{ add_link }}">Add a restaurant</a>{% endblocktrans %}
	<div class="pull-xs-right">
		<a title="Hack on GitHub" target="_blank" href="https://github.com/chlab/lunchy"><i class="fa fa-github fa-lg" aria-hidden="true"></i></a>
	</div>
{% endblock %}

lunch/templates/lunch/location_prompt.html
{% load i18n %}

<div class="card-block">
    <div class="card-title">{% trans "Where are you?" %}</div>
</div>

<div class="card-block">
    <form name="set_place" action="{% url 'lunch:index' %}" method="post">
        {% csrf_token %}
        <div id="place-search"></div>
    </form>
</div>

lunch/templates/lunch/meal_suggestion.html
{% load i18n %}
{% if meal_option and restaurant or restaurant %}
	<div class="card-block">
		<h4 class="card-title">{% trans "Not sure what to get for lunch?" %}</h4>
	</div>
	<div id="meal-suggestion">
		{% url 'lunch:restaurant_detail' restaurant.id as restaurant_link %}

		{% comment %} Restaurant and meal suggestion {% endcomment %}
		{% if meal_option and restaurant %}
			<p class="lead">
				{% blocktrans %}How about {{ meal_option }} from <a href="{{ restaurant_link }}">{{ restaurant }}</a>?{% endblocktrans %}
			</p>
		{% comment %} Restaurant suggestion without meal {% endcomment %}
		{% elif restaurant %}
			<p class="lead">
				{% blocktrans %}How about something from <a href="{{ restaurant_link }}">{{ restaurant }}</a>?{% endblocktrans %}
			</p>
		{% endif %}
	</div>

	<div class="card-block text-xs-center">
		{% url 'lunch:index' as reload_link %}
		{% blocktrans %}<a class="card-link" href="{{ reload_link }}">nope, something else</a>{% endblocktrans %}
	</div>
{% comment %} No restaurants {% endcomment %}
{% else %}
	<p class="lead">{% trans "Sadly, there are currently no meal options available :(" %}</p>
	{% url 'lunch:add_restaurant' as add_link %}
	<p class="lead">
		{% blocktrans %}Start by <a href="{{ add_link }}">adding one</a>!{% endblocktrans %}
	</p>
{% endif %}

lunch/templates/lunch/place_prompt.html
{% load i18n %}

<div class="card-block">
    <div class="card-title">{% trans "Where are you?" %}</div>
</div>

<div class="card-block">
    <form name="set_place" action="{% url 'lunch:index' %}" method="post">
        {% csrf_token %}
        <div id="place-search"></div>
    </form>
</div>

lunch/templates/lunch/restaurant.html
{% extends 'lunch/base.html' %}
{% load staticfiles %}

{% block content %}

<input type="hidden" id="place-facebook-id" value="{{restaurant.facebook_id}}">

<!-- facebook pic -->
<div class="card-block text-xs-center" id="restaurant-pic">
</div>

<!-- title -->
<div class="card-block text-xs-center">
	<h4 class="card-title">{{ restaurant }}</h4>
</div>

<!-- meal options -->
<div class="card-block">
	{% if restaurant.mealoption_set.exists %}
		<p>Meal options at this place:</p>
		<ul class="list-group">
			{% for option in restaurant.mealoption_set.all %}
				<li class="list-group-item">{{ option.name }}</li>
			{% endfor %}
		</ul>
		<p class="m-t-2">Want to add another one?</p>
	{% else %}
		<p>There are no meal options for this place yet. Why not add one:</p>
	{% endif %}

	<!-- add meal option form -->
	<form action="{% url 'lunch:restaurant_detail' restaurant.id %}" method="post">
		{% csrf_token %}
		<fieldset class="form-group">
			<div class="input-group">
				<input type="text" name="meal_option" class="form-control" placeholder="e.g. {{suggestion|default_if_none:'Pizza'}}" autofocus>
				<span class="input-group-btn">
	          		<button class="btn btn-secondary" type="button">Add</button>
	        	</span>
	        </div>
		</fieldset>
	</form>
</div>

<!-- links -->
<div class="card-block text-xs-center">
	<a class="card-link" href="{% url 'lunch:index' %}">back</a>
</div>

{% endblock %}

{% block javascript %}
    {% include 'lunch/snippets/facebook_js_sdk.html' %}
{% endblock %}

lunch/templates/lunch/snippets/facebook_js_sdk.html
<script>
	(function(d, s, id){
	   var js, fjs = d.getElementsByTagName(s)[0];
	   if (d.getElementById(id)) {return;}
	   js = d.createElement(s); js.id = id;
	   js.src = "//connect.facebook.net/en_US/sdk.js";
	   fjs.parentNode.insertBefore(js, fjs);
	 }(document, 'script', 'facebook-jssdk'));
</script>